title: "Starciad's Website"
email: "davilsfernandes.starciad.comu@gmail.com"
description: "Starciad's personal website, showcasing projects, books, and technology interests."

# Permalinks
permalink: /blog/:year/:month/:day/:title/ # Permalink structure for blog posts

markdown: kramdown

collections:
  books:
    output: true
    permalink: /books/:path/
  experiences:
    output: true
    permalink: /experiences/:path/
  learning:
    output: true
    permalink: /learning/:path/
  projects:
    output: true
    permalink: /projects/:path/
  technologies:
    output: true
    permalink: /technologies/:path/

defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"
  - scope:
      path: ""
      type: "experiences"
    values:
      layout: "experience"
  - scope:
      path: ""
      type: "learning"
    values:
      layout: "learning"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "technology"
    values:
      layout: "technology"
  - scope:
      path: ""
    values:
      layout: "default"